name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    tags: [ '*.*.*' ]
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: chasemcdougall/capstone-api:${{ github.ref_name }}, chasemcdougall/capstone-api:latest
      - name: Build
        if: github.event_name == 'pull_request' || github.ref_name == 'main'
        uses: docker/build-push-action@v5
