name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches-ignore: []

jobs:
  test:
    # This workflow is disabled due to cuda support which is not available on our current runners
    if: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Python Test
      run: python -m pytest
